import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ posts, quickLinks, more }) {
    return (
        <html lang='en'>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <main className='font-sans flex gap-[32px] row-start-2 items-center sm:items-start '>
                    <aside className='h-screen border-r w-[200px]'>
                        Sidebar
                    </aside>

                    {posts}

                    <aside className='flex-1 flex flex-col gap-5'>
                        {quickLinks}
                        {more}
                    </aside>
                </main>
            </body>
        </html>
    );
}
